name:                evkoverlay
version:             0.1.0.0
github:              "tux314159/evkoverlay"
license:             BSD-3-Clause
author:              "Isaac"
maintainer:          "tux314159@gmail.com"
copyright:           "2024 Isaac Yeo"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
synopsis:            Keypress display tool for Wayland using Linux's evdev
category:            Utilities

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tux314159/evkoverlay#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- text
- template-haskell
- lens
- h-raylib
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  evkoverlay:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evkoverlay

tests:
  evkoverlay-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - evkoverlay
